# Generated by Django 3.2.5 on 2021-07-06 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_userprofile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventInventoryRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_quantity', models.PositiveIntegerField()),
                ('approval_status', models.BooleanField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.event')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to=profiles_api.models.nameFile)),
                ('total_quantity', models.PositiveIntegerField()),
                ('avl_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[profiles_api.models.WhitelistEmailValidator(whitelist=['iiti.ac.in'])]),
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventinventoryrelationship',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.inventoryitem'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
