# Generated by Django 3.2.5 on 2021-07-06 20:43

from django.db import migrations, models
import profiles_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20210706_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinventoryrelationship',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_img',
            field=models.ImageField(blank=True, null=True, upload_to=profiles_api.models.itemNameFile),
        ),
    ]
